# ENVIAR DADOS DE ADDRESS
POST http://localhost:3000/address/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidHlwZVVzZXIiOjEsImlhdCI6MTczNzU5NDkwNywiZXhwIjoxNzM4MTk5NzA3fQ.MbFEccHgQXfvvT2w8hgvNHjZYW-3JhzJ-OR4XRoSyPU

{
    "complement": "complemento2",
    "number": 3213,
    "cep": "09371654",
    "cityId" : 128
}


