
### VISUALIZAR TODOS OS USER
GET http://localhost:3000/user
content-type: application/json
#Authorization: Bearer 


### CREATE USER
POST http://localhost:3000/user 
content-type: application/json

{
    "name": "lari",
    "phone": "11897813021",
    "email": "lari@gmail.com.br",
    "cpf" : "39518754546",
    "password": "lari123"
}

### IDENTIFIY USER FOR ID

GET http://localhost:3000/user/1
content-type: application/json




